Financroo aggregate accounts, transactions and balances
cloudentity/openbanking-sandbox pull request #24
Opened 2020-12-14 17:20 UTC by ikawalec

- define banks and login client credentials in config.yaml instead of env variables
- store connected banks in a mounted key-value store
- aggregate accounts, transactions and balances based on connected banks

TODO:
- [ ] add disconnect bank button

2020-12-16 10:06 UTC, bwereszczak approved these changes

2020-12-16 10:20 UTC, mbilski requested changes

2020-12-16 10:20 UTC, mbilski commented on financroo/bank_aggregation_routes.go
> +				c.String(http.StatusInternalServerError, fmt.Sprintf("failed to update user: %+v", err))
missing return

2020-12-16 10:20 UTC, mbilski commented on financroo/bank_aggregation_routes.go
> +				c.String(http.StatusInternalServerError, fmt.Sprintf("failed to update user: %+v", err))
same here

2020-12-16 10:20 UTC, mbilski commented on financroo/bank_aggregation_routes.go
> +				c.String(http.StatusInternalServerError, fmt.Sprintf("failed to update user: %+v", err))
same here

2020-12-16 10:20 UTC, mbilski commented on financroo/data/config.yaml
> +  ui_url: https://${APP_HOST}:8091
I don't like it that we need to sed this config file

2020-12-17 08:22 UTC, mbilski commented on financroo/config.go
> +	if bs, err = ioutil.ReadFile(config.YAMLConfigFile); err != nil {
wouldn't it be better to use viper to manage config files and env var instead of reading yaml file manually?

2020-12-17 08:26 UTC, ikawalec commented on financroo/config.go
> +	if bs, err = ioutil.ReadFile(config.YAMLConfigFile); err != nil {
If viper can read, validate if the env is provided, and also set the default env value I can replace it.

2020-12-29 12:31 UTC, ikawalec commented on financroo/config.go
> +	if bs, err = ioutil.ReadFile(config.YAMLConfigFile); err != nil {
I've changed it to use vuper. Please take a look.

2020-12-29 12:35 UTC, mbilski approved these changes

2020-12-29 12:51 UTC, merged