[AUT-2262]: POST /domestic-payments endpoint
cloudentity/openbanking-sandbox pull request #36
Opened 2021-02-03 21:27 UTC by dmartin5470

This PR adds an implementation for the POST /domestic-payments endpoint in the bank application. 

curl command to test (example payload taken from https://openbankinguk.github.io/read-write-api-site3/v3.1.6/resources-and-data-models/pisp/domestic-payments.html#post-domestic-payments)
```
curl -X POST "http://localhost:8070/domestic-payments" -H "Accept: application/json" -H "Authorization: Bearer {token}" \
--data '{
  "Data": {
    "ConsentId": "58923",
    "Initiation": {
      "InstructionIdentification": "ACME41",
      "EndToEndIdentification": "FRESCO.21302.GFX.20",
      "InstructedAmount": {
        "Amount": "165.88",
        "Currency": "GBP"
      },
      "CreditorAccount": {
        "SchemeName": "UK.OBIE.SortCodeAccountNumber",
        "Identification": "08080021325698",
        "Name": "ACME Inc",
        "SecondaryIdentification": "0002"
      },
      "RemittanceInformation": {
        "Reference": "FRESCO-101",
        "Unstructured": "Internal ops code 5120101"
      }
    }
  },
  "Risk": {
    "PaymentContextCode": "EcommerceGoods",
    "MerchantCategoryCode": "5967",
    "MerchantCustomerIdentification": "053598653254",
    "DeliveryAddress": {
      "AddressLine": [
        "Flat 7",
        "Acacia Lodge"
      ],
      "StreetName": "Acacia Avenue",
      "BuildingNumber": "27",
      "PostCode": "GU31 2ZZ",
      "TownName": "Sparsholt",
      "CountySubDivision": [
        "Wessex"
      ],
      "Country": "UK"
    }
  }
}' | jq
```

2021-02-08 13:07 UTC, ikawalec commented on bank/handler.go
> +	random := "12345"
You could use: `github.com/google/uuid`

2021-02-09 07:50 UTC, mbilski requested changes

2021-02-09 07:50 UTC, mbilski commented on bank/handler.go
> +	json.Unmarshal(data, &consent) //nolint
```
if err := json.Unmarshal(data, &consent); err != nil {
  panic(err)
}
```
let's do not ignore errors like this, it'll be a hell for someone to debug it if he updates this json and it's going to fail here

2021-02-09 07:51 UTC, ikawalec commented on bank/handler.go
> +		  "Status": "Authorized",
For OpenBanking UK it should be `Authorised`.

2021-02-09 08:58 UTC, mbilski requested changes

2021-02-09 08:58 UTC, mbilski commented on bank/payment_queue.go
> +		time.Sleep(10 * time.Second)
this will block the second call to create domestic payments for 10s, please do sth like
```
for payment := range pq.queue {
  time.AfterFunc(10 * time.Second, func() {
    if err := q.repo.SetDomesticPaymentStatus(*payment.Data.DomesticPaymentID, AcceptedSettlementCompleted); err != nil {
      logrus.WithError(err).Errorf("failed to blablabla")
    }
  }) 
}
```

please never ignore errors using // nolint

2021-02-09 09:00 UTC, mbilski requested changes

2021-02-09 09:00 UTC, mbilski commented on bank/handler.go
> +		if *introspectionResponse.Payload.Data.Status != "Authorised" { //nolint
please configure golangci-lint instead in `.golangci.yml` like
```
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - authorised
```
do not put // nolint unless there is no other way to handle it

2021-02-09 09:02 UTC, ikawalec commented
Please update PR description.

2021-02-09 09:05 UTC, ikawalec commented on bank/handler.go
> +)
use type alias and get rid of nolints

``` 
type DomesticPaymentStatus string

const (
  DomesticPaymentPendingStatus DomesticPaymentStatus = "Pending"
  ...
) 
```

2021-02-09 09:06 UTC, ikawalec commented on financroo/config_test.go
> +func TestConfig(t *testing.T) { //nolint
Why this change is required?

2021-02-09 16:08 UTC, dmartin5470 commented on financroo/config_test.go
> +func TestConfig(t *testing.T) { //nolint
I was getting this when running the linter:
```
financroo/config_test.go:11:1: Function TestConfig missing the call to method parallel (paralleltest)
```
But I just went ahead and added the parallel call to the test function

2021-02-09 16:11 UTC, dmartin5470 commented
PR description has been updated.

2021-02-17 14:21 UTC, dmartin5470 commented
If I'm not mistaken, I believe Risk should also be included in this struct? According to the domestic payments specification:
**"The Initiation and Risk sections of the domestic-payment request must match the Initiation and Risk sections of the corresponding domestic-payment-consent request."** Initiation is present in the response from the introspection endpoint, but Risk is not. Unless I am missing it somewhere else? 
```
// IntrospectOpenbankingDomesticPaymentConsentResponse introspect openbanking domestic payment consent response
//
// swagger:model IntrospectOpenbankingDomesticPaymentConsentResponse
type IntrospectOpenbankingDomesticPaymentConsentResponse struct {

	// Authentication Context Class Reference
	Acr string `json:"acr,omitempty"`

	// Active is a boolean indicator of whether or not the presented token
	// is currently active.  The specifics of a token's "active" state
	// will vary depending on the implementation of the authorization
	// server and the information it keeps about its tokens, but a "true"
	// value return for the "active" property will generally indicate
	// that a given token has been issued by this authorization server,
	// has not been revoked by the resource owner, and is within its
	// given time window of validity (e.g., after its issuance time and
	// before its expiration time).
	Active bool `json:"active,omitempty"`

	// Authentication Method References
	Amr []string `json:"amr"`

	// Audience contains a list of the token's intended audiences.
	Audience []string `json:"aud"`

	// authorisation
	Authorisation *DomesticPaymentConsentAuthorisation `json:"Authorisation,omitempty"`

	// ClientID is a client identifier for the OAuth 2.0 client that
	// requested this token.
	ClientID string `json:"client_id,omitempty"`

	// Unique identification as assigned to identify the domestic payment resource.
	ConsentID string `json:"consent_id,omitempty"`

	// Date and time at which the resource was created.
	// Format: date-time
	CreationDateTime strfmt.DateTime `json:"CreationDateTime,omitempty"`

	// delivery address
	DeliveryAddress *RiskDeliveryAddress `json:"DeliveryAddress,omitempty"`

	// Expires at is an integer timestamp, measured in the number of seconds
	// since January 1 1970 UTC, indicating when this token will expire.
	ExpiresAt int64 `json:"exp,omitempty"`

	// Extra is arbitrary data set by the session.
	Extra map[string]interface{} `json:"ext,omitempty"`

	// initiation
	Initiation *DomesticPaymentConsentDataInitiation `json:"Initiation,omitempty"`

	// Issued at is an integer timestamp, measured in the number of seconds
	// since January 1 1970 UTC, indicating when this token was
	// originally issued.
	IssuedAt int64 `json:"iat,omitempty"`

	// IssuerURL is a string representing the issuer of this token
	Issuer string `json:"iss,omitempty"`

	// Category code conform to ISO 18245, related to the type of services or goods the merchant provides for the transaction.
	// Max Length: 4
	// Min Length: 3
	MerchantCategoryCode string `json:"MerchantCategoryCode,omitempty"`

	// The unique customer identifier of the PSU with the merchant.
	// Max Length: 70
	// Min Length: 1
	MerchantCustomerIdentification string `json:"MerchantCustomerIdentification,omitempty"`

	// NotBefore is an integer timestamp, measured in the number of seconds
	// since January 1 1970 UTC, indicating when this token is not to be
	// used before.
	NotBefore int64 `json:"nbf,omitempty"`

	// Specifies the payment context
	// Enum: [[BillPayment EcommerceGoods EcommerceServices Other PartyToParty]]
	PaymentContextCode string `json:"PaymentContextCode,omitempty"`

	// Specifies to share the refund account details with PISP
	// Enum: [[No Yes]]
	ReadRefundAccount string `json:"ReadRefundAccount,omitempty"`

	// s c a support data
	SCASupportData *DomesticPaymentConsentSCASupportData `json:"SCASupportData,omitempty"`

	// Scope is a JSON string containing a space-separated list of
	// scopes associated with this token.
	Scope string `json:"scope,omitempty"`

	// ServerID is OAuth 2.0 authorization server identifier that
	// issued this token.
	ServerID string `json:"server_id,omitempty"`

	// Specifies the status of consent resource in code form.
	Status string `json:"Status,omitempty"`

	// Date and time at which the resource status was updated.
	// Format: date-time
	StatusUpdateDateTime strfmt.DateTime `json:"StatusUpdateDateTime,omitempty"`

	// Subject of the token, as defined in JWT [RFC7519].
	// Usually a machine-readable identifier of the resource owner who
	// authorized this token.
	Subject string `json:"sub,omitempty"`

	// TenantID identifies tenant where authorization server that
	// issued this token belongs to.
	TenantID string `json:"tenant_id,omitempty"`

	// TokenType is the introspected token's type, for example `access_token` or `refresh_token`.
	TokenType string `json:"token_type,omitempty"`

	// Username is a human-readable identifier for the resource owner who
	// authorized this token.
	Username string `json:"username,omitempty"`
}
```

2021-02-22 09:44 UTC, ikawalec commented
> If I'm not mistaken, I believe Risk should also be included in this struct? According to the domestic payments specification:
> **"The Initiation and Risk sections of the domestic-payment request must match the Initiation and Risk sections of the corresponding domestic-payment-consent request."** Initiation is present in the response from the introspection endpoint, but Risk is not. Unless I am missing it somewhere else?
> 
> ```
> // IntrospectOpenbankingDomesticPaymentConsentResponse introspect openbanking domestic payment consent response
> //
> // swagger:model IntrospectOpenbankingDomesticPaymentConsentResponse
> type IntrospectOpenbankingDomesticPaymentConsentResponse struct {
> 
> 	// Authentication Context Class Reference
> 	Acr string `json:"acr,omitempty"`
> 
> 	// Active is a boolean indicator of whether or not the presented token
> 	// is currently active.  The specifics of a token's "active" state
> 	// will vary depending on the implementation of the authorization
> 	// server and the information it keeps about its tokens, but a "true"
> 	// value return for the "active" property will generally indicate
> 	// that a given token has been issued by this authorization server,
> 	// has not been revoked by the resource owner, and is within its
> 	// given time window of validity (e.g., after its issuance time and
> 	// before its expiration time).
> 	Active bool `json:"active,omitempty"`
> 
> 	// Authentication Method References
> 	Amr []string `json:"amr"`
> 
> 	// Audience contains a list of the token's intended audiences.
> 	Audience []string `json:"aud"`
> 
> 	// authorisation
> 	Authorisation *DomesticPaymentConsentAuthorisation `json:"Authorisation,omitempty"`
> 
> 	// ClientID is a client identifier for the OAuth 2.0 client that
> 	// requested this token.
> 	ClientID string `json:"client_id,omitempty"`
> 
> 	// Unique identification as assigned to identify the domestic payment resource.
> 	ConsentID string `json:"consent_id,omitempty"`
> 
> 	// Date and time at which the resource was created.
> 	// Format: date-time
> 	CreationDateTime strfmt.DateTime `json:"CreationDateTime,omitempty"`
> 
> 	// delivery address
> 	DeliveryAddress *RiskDeliveryAddress `json:"DeliveryAddress,omitempty"`
> 
> 	// Expires at is an integer timestamp, measured in the number of seconds
> 	// since January 1 1970 UTC, indicating when this token will expire.
> 	ExpiresAt int64 `json:"exp,omitempty"`
> 
> 	// Extra is arbitrary data set by the session.
> 	Extra map[string]interface{} `json:"ext,omitempty"`
> 
> 	// initiation
> 	Initiation *DomesticPaymentConsentDataInitiation `json:"Initiation,omitempty"`
> 
> 	// Issued at is an integer timestamp, measured in the number of seconds
> 	// since January 1 1970 UTC, indicating when this token was
> 	// originally issued.
> 	IssuedAt int64 `json:"iat,omitempty"`
> 
> 	// IssuerURL is a string representing the issuer of this token
> 	Issuer string `json:"iss,omitempty"`
> 
> 	// Category code conform to ISO 18245, related to the type of services or goods the merchant provides for the transaction.
> 	// Max Length: 4
> 	// Min Length: 3
> 	MerchantCategoryCode string `json:"MerchantCategoryCode,omitempty"`
> 
> 	// The unique customer identifier of the PSU with the merchant.
> 	// Max Length: 70
> 	// Min Length: 1
> 	MerchantCustomerIdentification string `json:"MerchantCustomerIdentification,omitempty"`
> 
> 	// NotBefore is an integer timestamp, measured in the number of seconds
> 	// since January 1 1970 UTC, indicating when this token is not to be
> 	// used before.
> 	NotBefore int64 `json:"nbf,omitempty"`
> 
> 	// Specifies the payment context
> 	// Enum: [[BillPayment EcommerceGoods EcommerceServices Other PartyToParty]]
> 	PaymentContextCode string `json:"PaymentContextCode,omitempty"`
> 
> 	// Specifies to share the refund account details with PISP
> 	// Enum: [[No Yes]]
> 	ReadRefundAccount string `json:"ReadRefundAccount,omitempty"`
> 
> 	// s c a support data
> 	SCASupportData *DomesticPaymentConsentSCASupportData `json:"SCASupportData,omitempty"`
> 
> 	// Scope is a JSON string containing a space-separated list of
> 	// scopes associated with this token.
> 	Scope string `json:"scope,omitempty"`
> 
> 	// ServerID is OAuth 2.0 authorization server identifier that
> 	// issued this token.
> 	ServerID string `json:"server_id,omitempty"`
> 
> 	// Specifies the status of consent resource in code form.
> 	Status string `json:"Status,omitempty"`
> 
> 	// Date and time at which the resource status was updated.
> 	// Format: date-time
> 	StatusUpdateDateTime strfmt.DateTime `json:"StatusUpdateDateTime,omitempty"`
> 
> 	// Subject of the token, as defined in JWT [RFC7519].
> 	// Usually a machine-readable identifier of the resource owner who
> 	// authorized this token.
> 	Subject string `json:"sub,omitempty"`
> 
> 	// TenantID identifies tenant where authorization server that
> 	// issued this token belongs to.
> 	TenantID string `json:"tenant_id,omitempty"`
> 
> 	// TokenType is the introspected token's type, for example `access_token` or `refresh_token`.
> 	TokenType string `json:"token_type,omitempty"`
> 
> 	// Username is a human-readable identifier for the resource owner who
> 	// authorized this token.
> 	Username string `json:"username,omitempty"`
> }
> ```

The risk is currently embedded (in the struct that you pasted see: PaymentContextCode, MerchantCategoryCode, MerchantCustomerIdentification, DeliveryAddress).

2021-02-23 08:23 UTC, ikawalec approved these changes

2021-02-23 08:23 UTC, ikawalec commented on bank/data/data.json
> +      }}
Please remove it if it's not required.

2021-03-01 08:13 UTC, mbilski approved these changes

2021-03-01 15:11 UTC, merged