AUT-1895 Financroo app initial version
cloudentity/openbanking-sandbox pull request #8
Opened 2020-11-20 07:20 UTC by bwereszczak

![image](https://user-images.githubusercontent.com/4145041/99771135-e6645580-2b08-11eb-896a-10156ccecfe6.png)
![image](https://user-images.githubusercontent.com/4145041/99771145-ebc1a000-2b08-11eb-88e2-ce8b965f9b9c.png)
![image](https://user-images.githubusercontent.com/4145041/99771176-f67c3500-2b08-11eb-9858-19bb82ca7f32.png)
![image](https://user-images.githubusercontent.com/4145041/99771187-fb40e900-2b08-11eb-8994-188aff18a02e.png)
![image](https://user-images.githubusercontent.com/4145041/99771206-01cf6080-2b09-11eb-9554-2b0430fd5ddc.png)
![image](https://user-images.githubusercontent.com/4145041/99771221-0a279b80-2b09-11eb-9514-8672bf1a47a5.png)
![image](https://user-images.githubusercontent.com/4145041/99771226-0eec4f80-2b09-11eb-8577-d66836b9eac5.png)
![image](https://user-images.githubusercontent.com/4145041/99771237-13b10380-2b09-11eb-9461-f906a29c7e59.png)

2020-11-23 00:37 UTC, ikawalec requested changes

2020-11-23 00:37 UTC, ikawalec commented on bank/balances.go
> +func (s *Server) GetBalances() func(ctx *gin.Context) {
Please move it to handler.go (this is really simple app, and currently there is no need to keep this route in separate file).

2020-11-23 00:37 UTC, ikawalec commented on bank/balances.go
> +		c.JSON(200, balances)
You can use gin's one-liner method to do the same:

`c.File("balances.json")`

2020-11-23 00:37 UTC, ikawalec commented on bank/transactions.go
> +}
please move it to handler.go and use `c.File("transactions.json")`

2020-11-23 00:37 UTC, ikawalec commented on financroo/Dockerfile
> +COPY financroo/transactions.go .
In other apps we are using this syntax to copy all fields from directory to a docker:
`COPY financroo .`

2020-11-23 00:37 UTC, ikawalec commented on financroo/server.go
> +			"authorizationServerURL": os.Getenv("FINANCROO_AUTHORIZATION_SERVER_URL"),
Add `FINANCROO_` envs to Config struct and then use `s.Config.VariableName`

2020-11-23 00:37 UTC, ikawalec commented on financroo/web/app/Dockerfile
> +FROM nginx:1.17.10-alpine
Is `nginx` really necessary here? Can't you just serve js files using go backend?

2020-11-23 13:58 UTC, mbilski requested changes

2020-11-23 13:58 UTC, mbilski commented on financroo/balances.go
> +		var (
single var should be enough
```
var (
  resp *balances.GetBalancesOK
  err error
)
```

2020-11-23 13:58 UTC, mbilski commented on financroo/web/app/Dockerfile
> +FROM nginx:1.17.10-alpine
yeah, let's just use go to serve frontend, no need to use nginx

2020-11-25 03:21 UTC, lradosz approved these changes
Looks great for the initial version. I got it working without any issues and I've managed to go through the basic flow Open Banking Account Consent Flow. I've was able to  add the example Bank to Financroo. I do like that the Financroo is using ACP for Authn/Authz. It gives us the ability to connect to different IDPs for Authentication.

2020-11-27 06:18 UTC, bwereszczak commented on financroo/web/app/Dockerfile
> +FROM nginx:1.17.10-alpine
Frontend files are already served by go backend, this Dockerfile is not used any longer to build frontend app, will remove it.

2020-11-27 07:50 UTC, mbilski approved these changes
lgtm, just some minor issues

2020-11-27 07:50 UTC, mbilski commented on .dockerignore
> +financroo/web/app/node_modules
I think sth like this would work as well
```
**/node_modules
**/build
```
So there is no need to add more paths to this file if we add a web app to another service

2020-11-27 07:50 UTC, mbilski commented on docker-compose.yaml
> +      - ./data/ca.pem:/ca.pem
mounting just data should be enough
```
- ./data:/certs
```
this requires to change the paths to certs like CERT_FILE=/certs/tpp_cert.pem

2020-11-27 07:50 UTC, mbilski commented on financroo/accounts.go
> +		var (
single var should be enough

2020-11-27 07:50 UTC, mbilski commented on financroo/accounts.go
> +		token, _ := c.Cookie("token")
err is not checked

2020-12-02 07:51 UTC, mbilski approved these changes

2020-12-02 07:51 UTC, mbilski commented on data/seed.yaml
> +openbanking_consents:
there should be no consents in seed

2020-12-02 08:16 UTC, merged